urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib.auth import views as auth
from how2.core import views as core
from how2.mod_user import views as user
# admin system activated
from django.contrib import admin
admin.autodiscover()

handler404='howto.views.error404'

urlpatterns = patterns('',
    (r'^h2-admin/', include(admin.site.urls)),
    (r'^medios/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC, 'show_indexes':True}),
    (r'^404/$',core.error404),
    (r'^$',core.index),
    (r'^vote/(\d+)/(\d)/$',core.vote),
    (r'^accounts/login/$',core.login),
    (r'^accounts/logout/$',auth.logout),
    (r'^accounts/forgot/$',core.forgot),
    (r'^accounts/home/$',user.home),
    (r'^accounts/register/$',core.register),
    (r'^activate/(.+)/$',core.activate),
    (r'^accounts/profile/$',user.profile),
    (r'^howto/new/$',user.new),
    (r'^howto/view/(\d+)/$',user.view),
    (r'^howto/edit/(\d+)/$',user.edit),
    (r'^howto/suggestion/(\d+)/(\d+)/$',user.suggestion),
    (r'^howto/unselect/(\d+)/$',user.unselect),
    (r'^howto/translation',core.load_translation),
    (r'^contribute/category/$',user.category),
    (r'^contribute/how2/$',user.how2),
    (r'^invitations/$',core.find_on_how2),
    (r'^invitations/find_on_how2/$',core.find_on_how2),
    (r'^invitations/invite_by_email/$',core.invite_by_email),
    (r'^invitations/email_contacts/$',core.email_contacts),
    (r'^users/readers/$', user.readers),
    (r'^users/writers/$', user.writers),
    (r'^read/(.+)/$', user.read),
    (r'^load_template/$',core.load_template),
    (r'^load_translation/$',core.load_translation),
    (r'^check_username/$',core.check_username),
    (r'^check_email/$',core.check_email),
    (r'^(.+)/$',core.user),
)

core/models.py
 # -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.ForeignKey(User, unique=True, related_name='get_common_data')
    image = models.ImageField(upload_to='avatars/', null=True)
    birthday = models.DateField(null=True)
    country = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    role = models.CharField(max_length=100, null=True)
    interest = models.TextField(null=True)
    code = models.CharField(max_length=100, null=True)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    
    def __unicode__(self):
        return self.user.username

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=100)
    template = models.TextField()
    is_active = models.BooleanField(default=False)
    
    def __unicode__(self):
        return self.name

class Language(models.Model):
    id = models.CharField(max_length=2, primary_key=True)
    name = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.name

class How2(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    category = models.ForeignKey(Category, limit_choices_to={'is_active':True})
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User)
    rating = models.IntegerField(default=0, max_length=1)
    language = models.ForeignKey(Language)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    
    def __unicode__(self):
        return self.title

class Suggestion(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    how2 = models.ForeignKey(How2)
    author = models.ForeignKey(User)
    suggestion = models.TextField()
    status = models.BooleanField(default=False)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    
    def __unicode__(self):
        return self.howto.author.username

class Selected(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User)
    how2 = models.ForeignKey(How2)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    
    def __unicode__(self):
        return self.howto.title

class How2Contribution(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    mode = models.BooleanField()
    asker = models.ForeignKey(User, related_name='asker_how2')
    asked = models.ForeignKey(User, related_name='asked_how2', null=True)
    
    def __unicode__(self):
        return self.title

class UserMenu(models.Model):
    id = models.AutoField(primary_key=True)
    text = models.CharField(unique=True, max_length=30)
    link = models.CharField(max_length=30)
    tooltip = models.TextField(null=True)
    to = models.BooleanField(help_text='0=anyone,1=registered')
    
    def __unicode__(self):
        return self.text

class Reading(models.Model):
    id = models.AutoField(primary_key=True)
    reader = models.ForeignKey(User, related_name='reader')
    writer = models.ForeignKey(User, related_name='writers')
    
    def __unicode__(self):
        return self.reader.username
    
class Vote(models.Model):
    id = models.AutoField(primary_key=True)
    voter = models.ForeignKey(User)
    how2 = models.ForeignKey(How2)
 
class Translation(models.Model):
    id = models.AutoField(primary_key=True)
    orig = models.ForeignKey(How2)
    title = models.CharField(max_length=200)
    content = models.TextField()
    lang = models.ForeignKey(Language)
    
    def __unicode__(self):
        return self.title

templates/activate.html
{%extends 'main.html'%}
{%block content%}
    <form method="post" action=".">
        <input type="password" name="password" size="20" />
        <input type="submit" value="activar">
    </form>
{%endblock%}

templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{%block title%}{%endblock%}</title>
    {%block javascript%}
        <script type="application/x-javascript" src="/medios/js/jquery.js"></script>
        <script type="application/x-javascript" src="http://www.google.com/jsapi"></script>
        <script type="application/x-javascript" src="/medios/js/tiny_mce/tiny_mce.js"></script>
        <script type="application/x-javascript" src="/medios/js/core.js"></script>
        <script type="application/x-javascript" src="/medios/js/jquery.tinymce.js"></script>
    {%endblock%}
    {%block css%}
        <link rel="stylesheet" type="text/css" href="/medios/css/blueprint/screen.css" />
        <link rel="stylesheet" type="text/css" href="/medios/css/how2.css" />
    {%endblock css%}
</head>

<body>
    
    <div id="center" class="container prepend-1 append-1 prepend-top append-bottom">
        
        <div id="header" class="column span-5 first pull-1">
            {%block header%}{%endblock%}
        </div>
        
        <div id="searcher" class="column span-10 last push-1">
            {%block searcher%}{%endblock%}
        </div>
        
        <div id="users" class="column span-24 prepend-1 append-1 pull-1">
            {%block users%}{%endblock%}
        </div>
        
        <div id="content" class="column span-24 prepend-1 append-1 pull-1">
            {%block content%}{%endblock%}
        </div>
        
        <div id="footer" class="column span-24 prepend-1 append-1 pull-1 prepend-top">
            {%block footer%}{%endblock%}
        </div>
        
    </div>
    
</body>
</html>

templates/edit.html
{%extends 'view.html'%}

{%block content%}
    <script type="application/x-javascript">
        tiny();
    </script>
    <h1>Edicion de How2</h1>
    <div id="edit_how2" class="hcontent">
        <form method="post" action=".">
            {% csrf_token %}
            <table>
                {{how2_form.as_table}}
            </table>
            <input type="submit" value="Guardar" />
            <input type="button" value="Cancel">
        </form>
    </div>
{%endblock%}

templates/forgot.html
{%extends 'main.html'%}

{%block content%}
<div id="forgot">
    <form method="post" action=".">
        {% csrf_token %}
        <label for="user">Username or Email </label><input type="text" name="user">
        <input type="submit" value="Enviar">
    </form>
</div>
{%endblock%}

templates/home.html
{%extends 'main.html'%}

{%block content%}
    <script type="application/x-javascript">
        tiny();
    </script>
    <div id="how2_section" class="column span-24">
        <div id="selected" class="column span-12 tab">
            <h3 class="tabtitle">My selected how2s</h3>
            <div class="tabcontent">
                {%for s in selected%}
                    <p><a class="how2" href="/howto/view/{{s.how2.id}}">{{s.how2.title}} en {{s.how2.category.name}}</a> por <a href="/{{s.how2.author}}">{{s.how2.author}}</a> | <a href="/howto/unselect/{{s.id}}"><img src="/medios/img/delete.png" alt="unselect this"></a></p>
                {%endfor%}
            </div>
        </div>
        <div id="suggestions" class="column span-12 last tab">
            <h3 class="tabtitle">Suggestions</h3>
            <div class="tabcontent">
                {%for s in suggestions%}
                    <p><a href="/howto/suggestion/{{s.how2.id}}/{{s.id}}">Sugerencia en {{s.how2.title}} por {{s.author}} el {{s.date}}</a></p>
                {%endfor%}
            </div>
        </div>
        <div id="how2_main" class="column span-24">
            <div id="my_how2s_title" class="column span-12 first">
                <h1>Mis how2s</h1>
            </div>
            <div id="my_how2s_actions" class="column span-12 last">
                <a href="/howto/new/">Nuevo How2</a>
                <input type="button" id="contribute_how2_button" class="button" value="Sugerir how2" />
                <input type="button" id="contribute_category_button" class="button" value="Sugerir categoria" />
            </div>
            <div class="clear"></div>
            <div id="notice_ch2" class="notice" style="display:none;">Tu sugerencia de How2 ha sido publicada, para que la comunidad revise</div>
            <div id="notice_cc" class="notice" style="display: none;">Tu sugerencia de Categoría será revisada</div>
            <div id="error" class="error" style="display:none;">Debes llenar todos los campos</div>
            <div id="my_how2s" class="column span-24">
                <div id="contribute_how2" style="display:none;" class="hcontent">
                    <h5>Escribe el titulo y una breve descripcion, que explique el tema a tratar</h5>
                    <form id="ch2" method="post" action="/contribute/how2/">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <td><input type="text" name="title" id="title_contribute_how2" value="Title" /></td>
                            </tr>
                            <tr>
                                <td><textarea name="description" id="description_contribute_how2" cols="45" rows="5"></textarea></td>
                            </tr>
                            <tr>
                                <td>
                                    <select name="mode_ask" id="mode_ask">
                                        <option value="0"> Public </option>
                                        <option value="1"> Private </option>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td id="ask_to_hidden" style="display:none;">
                                    <select name="writer_to_ask">
                                        <option value="default">Elije...</option>
                                        {%for w in writers%}
                                            <option value="{{w.writer}}">{{w.writer}}</option>
                                        {%endfor%}
                                    </select>
                                </td>
                            </tr>
                        </table>
                        <input type="submit" name="enviar" value="Enviar" class="button" />
                    </form>
                </div>
                <div id="contribute_category" style="display:none;" class="hcontent">
                    <h5>Sugerencia de categoria</h5>
                    <form id="cc" method="post" action="/contribute/category/">
                        {% csrf_token %}
                        <table>
                            {{category_form.as_table}}
                        </table>
                        <input type="submit" name="enviar" value="Enviar" class="button"/>
                    </form>
                </div>
                <div id="howtos_list">
                    <table>
                        <tr>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Category</th>
                            <th>Rating</th>
                        </tr>
                    {%if how2_list%}
                        {%for h in how2_list%}
                        <tr>
                            <td><a class="how2" href="/howto/view/{{h.id}}">{{h.title}}</a></td>
                            <td>{{h.date}}</td>
                            <td>{{h.category}}</td>
                            <td>{{h.rating}}</td>
                        </tr>
                        {%endfor%}
                    </table>
                    {%else%}
                    </table>
                    <p class="empty">No one how2</p>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
{%endblock%}

templates/index.html
{%extends 'main.html'%}

{%block content%}
    {%if not empty%}
        {%if orig_res or trans_res%}
        Originals
        <table>
                {%for o in orig_res%}
                    <tr>
                        <td><a class="how2" href="/howto/view/{{o.id}}">{{o.title}}</a></td>
                    </tr>
                {%endfor%}
        </table>
        Translations
        <table>
                {%for t in trans_res%}
                    <tr>
                        <td><a class="how2" href="/howto/view/{{t.id}}">{{t.title}}</a></td>
                    </tr>
                {%endfor%}
        </table>
        {%else%}
                <p class="emtpy">No results</p>
        {%endif%}
    {%else%}
        <div id="messages" class="column span-24">
            <h1>Welcome to How2!</h1>
            <p>Why i want to use How2?</p>
            <p>
                How2 is an idea to create a site where you can find answers written
                by another person, when you ask the classicly question "How to ... ?".
                We don't know, maybe anything professional or just cotidian.
            </p>
            <p>
                But the idea is than all that would be here =D in How2 and you won't be
                searching hours and hours in google, just pick on a category and begin or
                write keywords on the search field and get the procedure to do that. Thanks
            </p>
        </div>
        <div class="clear"></div>
        <div id="quick_tips" class="column span-11 append-1 first">
            <h2>Tips</h2>
            <p>
                Please when you'll write a how2, begin the answer with the word how on
                your language of course (for example: como, come, how, etc).
                Please use accent and all the simbols in your native language.
            </p>
        </div>
        <div id="how2_suggested" class="column span-11 prepend-1 last">
            <h2>Comunity's Requestions</h2>
            <div id="how2_suggested_content">
                {%for h in h2c%}
                        <p>{{h.title}} por {{h.asker}}</p>
                {%endfor%}
            </div>
        </div>
        <div class="clear"></div>
        <div id="categories" class="column span-24">
            <h2>Categorias</h2>
        </div>
    {%endif%}
{%endblock%}

templates/main.html
{%extends 'base.html'%}
{%block title%}
    {{ws_name}} | {{ws_slogan}}
{%endblock%}

{%block header%}
    <div id="logo" class="column span-5">
        <a href="/"><img src="/medios/img/{{ws_logo}}" /></a>
    </div>
{%endblock%}

{%block searcher%}
        <form class="searcher" method="post" action="/">
            <input type="text" name="word" size="40" />
            <input class="button" value="Buscar" type="submit" />
        </form>
{%endblock%}

{%block users%}
    {%if user.is_authenticated%}
        <div id="tabuser" class="column span-12 first prepend-1 pull-1">
            <div class="column span-3 first"><img src="/medios/{{avatar}}"></div>
            <div class="column span-8 last">
                {{welcome}} {{user.username}},
                <a href="/{{user.username}}">{{h2s}} how2s</a>
                <a href="/users/readers/">{{rds}} readers</a>
                <a href="/users/writers/">{{wts}} writers</a>
            </div>
        </div>
        <div id="usermenu" class="column span-12 last push-1">
            {%for m in user_menu%}
                <a id="{{m.text}}" href="{{m.link}}">{{m.text}}</a>
            {%endfor%}
        </div>
    {%else%}
        <div id="nousermenu" class="column span-24 pull-1">
            {%for n in no_user_menu%}
                <a href="{{n.link}}">{{n.text}}</a>
            {%endfor%}
        </div>
    {%endif%}
{%endblock%}

{%block footer%}
    <p>By <a href="{{ws_footer_link}}" target="_blank">{{ws_footer_content}}</a></p>
{%endblock%}

templates/message.html
{%extends 'main.html'%}

{%block content%}
<p>{{message}}</p>
<p><a href="{{link}}">{{text}}</a></p>
{%endblock%}

templates/new.html
{%extends 'main.html'%}
{%block content%}
<script type="application/x-javascript">
    tiny();
</script>
<h1>Nuevo How2</h1>
<div id="new_how2" class="hcontent">
    <form method="post" action=".">
        {% csrf_token %}
        <table>
            {{new_how2_form.as_table}}
        </table>
        <input type="submit" value="Save" />
        <input type="button" value="Cancel" />
    </form>
</div>
{%endblock%}

templates/readers.html
{%extends 'main.html'%}

{%block content%}
<div class="user_data">
    {%for r in readers%}
        <p>{{r.reader}}</p>
    {%endfor%}
</div>
{%endblock%}

templates/register.html
{%extends 'main.html'%}
{%block content%}
<div id="register">
    <div id="form_error" class="error" style="display:none;">Llena todos los campos</div>
    <div id="email_error" class="error" style="display:none;">Correo electrónico invalido</div>
    <form method="post" action=".">
        {% csrf_token %}
        <table>
            {{register_form.as_table}}
        </table>
        <div id="u_notice" class="notice" style="display:none;">Nombre de usuario disponible</div>
        <div id="u_error" class="error" style="display:none;">Nombre de usuario no disponible</div>
        <div id="e_notice" class="notice" style="display:none;">Correo electr&oacute;nico disponible</div>
        <div id="e_error" class="error" style="display:none;">Correo electr&oacute;nico no disponible</div>
        <input type="submit" value="Registrar">
    </form>
</div>
{%endblock%}

templates/suggestions.html
{%extends 'main.html'%}

{%block content%}
    {%for s in suggestions%}
        <p>{{s}}</p>
    {%endfor%}
{%endblock%}

templates/view.html
{%extends 'main.html'%}

{%block content%}
    <div id="view" class="column span-24">
        <label for="languages">Which language do you want to read this how2?</label>
        <select id="id_lang" name="lang" howto="{{how2.id}}">
            {%for l in languages%}
                <option value="{{l.id}}">{{l.name}}</option>
            {%endfor%}
        </select>
        <p id="how2_title">{{how2.title}}</p>
        <p>por: {{how2.author}}</p>
        <p ><div id="how2_content" class="column span-22 prepend-1 append-1">{{how2.content|safe}}</div></p>
        {%if owner and user.is_authenticated%}
            <p><a  href="/howto/edit/{{how2.id}}">Editar</a></p>
        {%else%}
                {%if can_vote%}
                    <div id="rating">
                        <img src="/medios/img/star.jpeg" class="star_vote" action="/vote/{{how2.id}}/1/" />
                        <img src="/medios/img/star.jpeg" class="star_vote" action="/vote/{{how2.id}}/2/" />
                        <img src="/medios/img/star.jpeg" class="star_vote" action="/vote/{{how2.id}}/3/" />
                        <img src="/medios/img/star.jpeg" class="star_vote" action="/vote/{{how2.id}}/4/" />
                        <img src="/medios/img/star.jpeg" class="star_vote" action="/vote/{{how2.id}}/5/" />
                    </div>
                {%endif%}
                {%if not selected%}
                    <form method="post" action=".">
                        <input type="submit" name="select" value="Seleccionar" class="button">
                    </form>
                {%endif%}
                <script type="application/x-javascript">
                    tiny();
                </script>
                <input type="button" id="suggest_how2_button" class="button" value="Suggest"/>
                <div id="suggest_how2" style="display:none;" class="hcontent">
                    <p>Nueva sugerencia</p>
                    <form method="post" action=".">
                        <textarea name="suggestion" cols="45" rows="15"></textarea>
                        <input type="submit" value="Save"/>
                    </form>
                </div>
                <div class="clear"></div>
                <div class="suggestion">
                    {%for s in suggestions%}
                        {{s.author}}:
                        {{s.suggestion|safe}}
                    {%endfor%}
                </div>
        {%endif%}
    </div>
{%endblock%}

templates/writers.html
{%extends 'main.html'%}

{%block content%}
<div class="user_data">
    {%for w in writers%}
        <p>{{w.writer}}</p>
    {%endfor%}
</div>
{%endblock%}